<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/xsl" href="bank.xsl"?>

<!DOCTYPE banks [
		<!ELEMENT banks (branch+)>
		<!ELEMENT branch (id,name,street,city,region,country,clients*)>
		<!ELEMENT id (#PCDATA)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT street (#PCDATA)>
		<!ELEMENT city (#PCDATA)>
		<!ELEMENT region (#PCDATA)>
		<!ELEMENT country (#PCDATA)>
		<!ELEMENT clients (id,firstName,lastName,email,phoneNumber,cards*)>
		<!ELEMENT firstName (#PCDATA)>
		<!ELEMENT lastName (#PCDATA)>
		<!ELEMENT email (#PCDATA)>
		<!ELEMENT phoneNumber (#PCDATA)>
		<!ELEMENT cards (number,type,cvv,expiresAt)>
		<!ELEMENT number (#PCDATA)>
		<!ELEMENT type (#PCDATA)>
		<!ELEMENT cvv (#PCDATA)>
		<!ELEMENT expiresAt (#PCDATA)>
		]>

<banks>
  <branch>
    <id>9337c59a-3df1-40c7-b106-6c13033264ca</id>
    <name>Corkery Inc</name>
    <street>58 Sycamore Place</street>
    <city>Jacksonville</city>
    <region>Florida</region>
    <country>United States</country>
    <clients>
      <id>b17fd735-a6a9-4301-baa2-48544c2de237</id>
      <firstName>Jeddy</firstName>
      <lastName>Elmhurst</lastName>
      <email>jelmhurst0@examiner.com</email>
      <phoneNumber>501-321-7367</phoneNumber>
      <cards>
        <number>201652668144335</number>
        <type>diners-club-enroute</type>
        <cvv>721</cvv>
        <expiresAt>2016-03</expiresAt>
      </cards>
      <cards>
        <number>30050196044761</number>
        <type>diners-club-carte-blanche</type>
        <cvv>210</cvv>
        <expiresAt>2018-05</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>3bbada21-839d-4684-8cf6-7551081f932a</id>
      <firstName>Arlene</firstName>
      <lastName>Greenroad</lastName>
      <email>agreenroad1@squarespace.com</email>
      <phoneNumber>788-576-7723</phoneNumber>
      <cards>
        <number>6392323790875883</number>
        <type>instapayment</type>
        <cvv>767</cvv>
        <expiresAt>2013-12</expiresAt>
      </cards>
      <cards>
        <number>3562843996671795</number>
        <type>jcb</type>
        <cvv>738</cvv>
        <expiresAt>2019-09</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>25c7b46c-e9b7-49d7-8df2-06d58d587dd3</id>
      <firstName>Kiley</firstName>
      <lastName>Ceschelli</lastName>
      <email>kceschelli2@linkedin.com</email>
      <phoneNumber>914-860-4254</phoneNumber>
      <cards>
        <number>5610758113792836</number>
        <type>bankcard</type>
        <cvv>187</cvv>
        <expiresAt>2015-12</expiresAt>
      </cards>
      <cards>
        <number>491117107787495799</number>
        <type>switch</type>
        <cvv>420</cvv>
        <expiresAt>2019-03</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>d2cb48e2-3f17-40c4-a6c0-df42df86960a</id>
    <name>Botsford and Sons</name>
    <street>88993 Quincy Parkway</street>
    <city>Reno</city>
    <region>Nevada</region>
    <country>United States</country>
    <clients>
      <id>87a8c19e-89e6-46fb-92fc-76aead7e6d7b</id>
      <firstName>Dulcie</firstName>
      <lastName>Blaase</lastName>
      <email>dblaase3@diigo.com</email>
      <phoneNumber>850-883-4739</phoneNumber>
      <cards>
        <number>6333498721113893</number>
        <type>switch</type>
        <cvv>324</cvv>
        <expiresAt>2017-02</expiresAt>
      </cards>
      <cards>
        <number>50206915331261996</number>
        <type>maestro</type>
        <cvv>579</cvv>
        <expiresAt>2015-02</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>1c951ed7-7e2c-49f0-a48e-a5b0a24102d4</id>
      <firstName>Patric</firstName>
      <lastName>Mattia</lastName>
      <email>pmattia4@discuz.net</email>
      <phoneNumber>361-580-2342</phoneNumber>
      <cards>
        <number>6304724094468015621</number>
        <type>maestro</type>
        <cvv>813</cvv>
        <expiresAt>2012-06</expiresAt>
      </cards>
      <cards>
        <number>3554320078586357</number>
        <type>jcb</type>
        <cvv>595</cvv>
        <expiresAt>2015-06</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>ddf1d898-f5ea-4f71-939c-4123e37b2c67</id>
      <firstName>Jo ann</firstName>
      <lastName>Drayson</lastName>
      <email>jdrayson5@imdb.com</email>
      <phoneNumber>515-367-8962</phoneNumber>
      <cards>
        <number>3542846442903006</number>
        <type>jcb</type>
        <cvv>895</cvv>
        <expiresAt>2013-11</expiresAt>
      </cards>
      <cards>
        <number>5602211621009640</number>
        <type>bankcard</type>
        <cvv>782</cvv>
        <expiresAt>2019-06</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>bb20b2ef-3d99-4755-bf7f-f6290083c434</id>
    <name>Kutch and Sons</name>
    <street>0993 Ruskin Place</street>
    <city>Lakeland</city>
    <region>Florida</region>
    <country>United States</country>
    <clients>
      <id>e297f1ff-da94-4bdb-ada5-6028bb442732</id>
      <firstName>Abdel</firstName>
      <lastName>Hintzer</lastName>
      <email>ahintzer6@amazon.de</email>
      <phoneNumber>403-654-9286</phoneNumber>
      <cards>
        <number>5893946596035249</number>
        <type>maestro</type>
        <cvv>179</cvv>
        <expiresAt>2018-11</expiresAt>
      </cards>
      <cards>
        <number>3531208224680554</number>
        <type>jcb</type>
        <cvv>977</cvv>
        <expiresAt>2021-12</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>4f971fab-a080-4abf-adb5-28731a647388</id>
      <firstName>Brigit</firstName>
      <lastName>Outerbridge</lastName>
      <email>bouterbridge7@list-manage.com</email>
      <phoneNumber>761-163-5181</phoneNumber>
      <cards>
        <number>3562115203852413</number>
        <type>jcb</type>
        <cvv>939</cvv>
        <expiresAt>2019-10</expiresAt>
      </cards>
      <cards>
        <number>5602229261032631</number>
        <type>china-unionpay</type>
        <cvv>751</cvv>
        <expiresAt>2014-11</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>6524cb37-2003-49a6-95af-0e712e17abe7</id>
      <firstName>Helen</firstName>
      <lastName>Ginnally</lastName>
      <email>hginnally8@statcounter.com</email>
      <phoneNumber>260-578-3021</phoneNumber>
      <cards>
        <number>201836873274157</number>
        <type>diners-club-enroute</type>
        <cvv>828</cvv>
        <expiresAt>2014-12</expiresAt>
      </cards>
      <cards>
        <number>3547872399476098</number>
        <type>jcb</type>
        <cvv>430</cvv>
        <expiresAt>2012-10</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>dbc9688d-294b-4a2f-a373-1ab7bd9fabba</id>
    <name>Torphy, Dickinson and Walter</name>
    <street>75 Loomis Alley</street>
    <city>Baltimore</city>
    <region>Maryland</region>
    <country>United States</country>
    <clients>
      <id>cb2ddb3f-eebf-45fd-9894-f1af9465209f</id>
      <firstName>Zerk</firstName>
      <lastName>Ingry</lastName>
      <email>zingry9@slashdot.org</email>
      <phoneNumber>986-688-7361</phoneNumber>
      <cards>
        <number>3582836124205276</number>
        <type>jcb</type>
        <cvv>391</cvv>
        <expiresAt>2017-03</expiresAt>
      </cards>
      <cards>
        <number>3550606794068074</number>
        <type>jcb</type>
        <cvv>992</cvv>
        <expiresAt>2018-05</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>df5107cd-acd5-458e-9ba5-01d646d849bb</id>
      <firstName>Maitilde</firstName>
      <lastName>Marwood</lastName>
      <email>mmarwooda@boston.com</email>
      <phoneNumber>526-110-2435</phoneNumber>
      <cards>
        <number>3587199784867918</number>
        <type>jcb</type>
        <cvv>452</cvv>
        <expiresAt>2019-10</expiresAt>
      </cards>
      <cards>
        <number>633322821736065796</number>
        <type>switch</type>
        <cvv>179</cvv>
        <expiresAt>2013-08</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>8bff6944-c721-4727-b737-dd64696d8e46</id>
      <firstName>Jim</firstName>
      <lastName>Middleton</lastName>
      <email>jmiddletonb@jiathis.com</email>
      <phoneNumber>246-739-5678</phoneNumber>
      <cards>
        <number>3581666378731979</number>
        <type>jcb</type>
        <cvv>426</cvv>
        <expiresAt>2017-10</expiresAt>
      </cards>
      <cards>
        <number>5391753203532478</number>
        <type>mastercard</type>
        <cvv>714</cvv>
        <expiresAt>2018-07</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>23bac6dd-006c-4331-9bc4-f76f07992663</id>
    <name>Zboncak, Schaefer and Metz</name>
    <street>1088 Kensington Court</street>
    <city>Columbus</city>
    <region>Ohio</region>
    <country>United States</country>
    <clients>
      <id>a6ca87e7-bb09-4ece-9c05-529762a5d4f4</id>
      <firstName>Ardys</firstName>
      <lastName>Bech</lastName>
      <email>abechc@nature.com</email>
      <phoneNumber>504-408-2724</phoneNumber>
      <cards>
        <number>3564088650308676</number>
        <type>jcb</type>
        <cvv>841</cvv>
        <expiresAt>2020-06</expiresAt>
      </cards>
      <cards>
        <number>503871739529189591</number>
        <type>maestro</type>
        <cvv>767</cvv>
        <expiresAt>2016-11</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>57209502-04b4-4e90-b536-d66f583fe664</id>
      <firstName>Rivi</firstName>
      <lastName>Verring</lastName>
      <email>rverringd@51.la</email>
      <phoneNumber>637-916-0222</phoneNumber>
      <cards>
        <number>30383655424921</number>
        <type>diners-club-carte-blanche</type>
        <cvv>522</cvv>
        <expiresAt>2021-02</expiresAt>
      </cards>
      <cards>
        <number>3568291833749792</number>
        <type>jcb</type>
        <cvv>320</cvv>
        <expiresAt>2021-05</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>039f288c-374f-42a3-b398-96ffd2c141d3</id>
      <firstName>Gretchen</firstName>
      <lastName>Allabarton</lastName>
      <email>gallabartone@europa.eu</email>
      <phoneNumber>971-907-3467</phoneNumber>
      <cards>
        <number>3554415677952156</number>
        <type>jcb</type>
        <cvv>831</cvv>
        <expiresAt>2022-03</expiresAt>
      </cards>
      <cards>
        <number>5284382655667473</number>
        <type>mastercard</type>
        <cvv>715</cvv>
        <expiresAt>2012-03</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>7142cbf0-816c-4138-867e-9e54417b8a5d</id>
    <name>Lind, Kerluke and Tillman</name>
    <street>47 Dakota Plaza</street>
    <city>Fermont</city>
    <region>Qu√©bec</region>
    <country>Canada</country>
    <clients>
      <id>7924ecf4-c645-4c0f-9070-93ef967b2d6d</id>
      <firstName>Maurits</firstName>
      <lastName>Gabbitas</lastName>
      <email>mgabbitasf@fda.gov</email>
      <phoneNumber>784-319-0578</phoneNumber>
      <cards>
        <number>3537404165649344</number>
        <type>jcb</type>
        <cvv>832</cvv>
        <expiresAt>2013-04</expiresAt>
      </cards>
      <cards>
        <number>3573187817925650</number>
        <type>jcb</type>
        <cvv>983</cvv>
        <expiresAt>2020-07</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>293908a2-7687-4365-8d63-c49a65b49e4a</id>
      <firstName>Vinita</firstName>
      <lastName>Spires</lastName>
      <email>vspiresg@blogspot.com</email>
      <phoneNumber>858-249-3659</phoneNumber>
      <cards>
        <number>3580319474018377</number>
        <type>jcb</type>
        <cvv>950</cvv>
        <expiresAt>2022-04</expiresAt>
      </cards>
      <cards>
        <number>374288005264329</number>
        <type>americanexpress</type>
        <cvv>572</cvv>
        <expiresAt>2013-07</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>86bc3871-6b9c-4711-b034-d9362742e392</id>
      <firstName>Augusta</firstName>
      <lastName>Signoret</lastName>
      <email>asignoreth@lulu.com</email>
      <phoneNumber>809-876-5888</phoneNumber>
      <cards>
        <number>6334201625480643</number>
        <type>solo</type>
        <cvv>310</cvv>
        <expiresAt>2022-11</expiresAt>
      </cards>
      <cards>
        <number>374288399334506</number>
        <type>americanexpress</type>
        <cvv>284</cvv>
        <expiresAt>2012-04</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>1a5fe502-2f0a-4f70-b6b6-66691af66181</id>
    <name>Zemlak Group</name>
    <street>88 Lillian Crossing</street>
    <city>Hollywood</city>
    <region>Florida</region>
    <country>United States</country>
    <clients>
      <id>89e34459-e278-497b-a413-d1635b0a92de</id>
      <firstName>Yankee</firstName>
      <lastName>Weiss</lastName>
      <email>yweissi@smugmug.com</email>
      <phoneNumber>722-897-5945</phoneNumber>
      <cards>
        <number>5610383067602384</number>
        <type>china-unionpay</type>
        <cvv>195</cvv>
        <expiresAt>2018-02</expiresAt>
      </cards>
      <cards>
        <number>5010121827243347</number>
        <type>mastercard</type>
        <cvv>677</cvv>
        <expiresAt>2018-07</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>454ba63a-bc71-4cb3-936d-c455a5f8e249</id>
      <firstName>Rochester</firstName>
      <lastName>Mullenger</lastName>
      <email>rmullengerj@eepurl.com</email>
      <phoneNumber>931-320-4382</phoneNumber>
      <cards>
        <number>201608373995965</number>
        <type>diners-club-enroute</type>
        <cvv>795</cvv>
        <expiresAt>2015-01</expiresAt>
      </cards>
      <cards>
        <number>3583427351604693</number>
        <type>jcb</type>
        <cvv>132</cvv>
        <expiresAt>2016-11</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>606513fa-eb07-434d-9999-6bfd8a54e14c</id>
      <firstName>Cammi</firstName>
      <lastName>Snowsill</lastName>
      <email>csnowsillk@altervista.org</email>
      <phoneNumber>246-586-5847</phoneNumber>
      <cards>
        <number>3542682991965728</number>
        <type>jcb</type>
        <cvv>270</cvv>
        <expiresAt>2018-07</expiresAt>
      </cards>
      <cards>
        <number>3544183850468357</number>
        <type>jcb</type>
        <cvv>938</cvv>
        <expiresAt>2020-05</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>989f9d79-7454-436d-aa6e-19a80e5292b5</id>
    <name>Moore-Schneider</name>
    <street>444 6th Place</street>
    <city>Jackson</city>
    <region>Mississippi</region>
    <country>United States</country>
    <clients>
      <id>0a95895b-c01f-473e-8c0e-79c5c165ef6f</id>
      <firstName>Josiah</firstName>
      <lastName>Mechic</lastName>
      <email>jmechicl@spiegel.de</email>
      <phoneNumber>815-772-8405</phoneNumber>
      <cards>
        <number>6767056701576871911</number>
        <type>solo</type>
        <cvv>933</cvv>
        <expiresAt>2019-10</expiresAt>
      </cards>
      <cards>
        <number>675990281684872564</number>
        <type>switch</type>
        <cvv>581</cvv>
        <expiresAt>2016-03</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>0efba7b1-580b-44ca-bcc5-86a4db42c2b2</id>
      <firstName>Kalila</firstName>
      <lastName>Munslow</lastName>
      <email>kmunslowm@jimdo.com</email>
      <phoneNumber>816-391-6948</phoneNumber>
      <cards>
        <number>4017957226187460</number>
        <type>visa</type>
        <cvv>505</cvv>
        <expiresAt>2020-11</expiresAt>
      </cards>
      <cards>
        <number>3529495623133459</number>
        <type>jcb</type>
        <cvv>605</cvv>
        <expiresAt>2013-05</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>2271ad4d-7746-472f-ba8e-dd8b0e0c573b</id>
      <firstName>Valli</firstName>
      <lastName>Blesli</lastName>
      <email>vbleslin@uiuc.edu</email>
      <phoneNumber>342-757-1632</phoneNumber>
      <cards>
        <number>3535502987682732</number>
        <type>jcb</type>
        <cvv>614</cvv>
        <expiresAt>2018-10</expiresAt>
      </cards>
      <cards>
        <number>5602224521511151</number>
        <type>bankcard</type>
        <cvv>494</cvv>
        <expiresAt>2022-03</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>143f3303-3621-4fd2-987c-46a387afcd83</id>
    <name>Effertz LLC</name>
    <street>58459 Clove Park</street>
    <city>Viking</city>
    <region>Alberta</region>
    <country>Canada</country>
    <clients>
      <id>3489dbe1-7adf-45cf-91ae-e6814f270c85</id>
      <firstName>Kimberlyn</firstName>
      <lastName>Schneidau</lastName>
      <email>kschneidauo@paginegialle.it</email>
      <phoneNumber>447-861-0619</phoneNumber>
      <cards>
        <number>372417423376314</number>
        <type>americanexpress</type>
        <cvv>134</cvv>
        <expiresAt>2020-03</expiresAt>
      </cards>
      <cards>
        <number>4017958756397</number>
        <type>visa</type>
        <cvv>240</cvv>
        <expiresAt>2015-06</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>911e2dfb-fdfb-4c71-b739-727feffebe31</id>
      <firstName>Adams</firstName>
      <lastName>Tourner</lastName>
      <email>atournerp@xrea.com</email>
      <phoneNumber>561-156-8042</phoneNumber>
      <cards>
        <number>3571689679749021</number>
        <type>jcb</type>
        <cvv>639</cvv>
        <expiresAt>2021-09</expiresAt>
      </cards>
      <cards>
        <number>5602239115353059</number>
        <type>china-unionpay</type>
        <cvv>880</cvv>
        <expiresAt>2016-09</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>61820637-9a66-4b27-9b87-ae7cc378f8bd</id>
      <firstName>Benjamen</firstName>
      <lastName>Radke</lastName>
      <email>bradkeq@stanford.edu</email>
      <phoneNumber>341-150-7718</phoneNumber>
      <cards>
        <number>675921193140138585</number>
        <type>switch</type>
        <cvv>173</cvv>
        <expiresAt>2019-10</expiresAt>
      </cards>
      <cards>
        <number>5602217977707247298</number>
        <type>china-unionpay</type>
        <cvv>656</cvv>
        <expiresAt>2019-06</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>a88f9964-5b2d-42c4-8ded-6a5eb76b27d7</id>
    <name>Von Inc</name>
    <street>00 Basil Hill</street>
    <city>Morden</city>
    <region>Manitoba</region>
    <country>Canada</country>
    <clients>
      <id>e62255b1-49cf-49ea-b9c6-79cf854eea59</id>
      <firstName>Lyndel</firstName>
      <lastName>Shier</lastName>
      <email>lshierr@thetimes.co.uk</email>
      <phoneNumber>690-481-3288</phoneNumber>
      <cards>
        <number>6709977805584000</number>
        <type>laser</type>
        <cvv>829</cvv>
        <expiresAt>2017-11</expiresAt>
      </cards>
      <cards>
        <number>4508162092778130</number>
        <type>visa-electron</type>
        <cvv>238</cvv>
        <expiresAt>2013-07</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>b259129f-856f-43c3-a76b-0f9e42e4107e</id>
      <firstName>Anatol</firstName>
      <lastName>Wiffler</lastName>
      <email>awifflers@deviantart.com</email>
      <phoneNumber>621-662-8143</phoneNumber>
      <cards>
        <number>5610948831598322</number>
        <type>bankcard</type>
        <cvv>829</cvv>
        <expiresAt>2022-10</expiresAt>
      </cards>
      <cards>
        <number>374622469311723</number>
        <type>americanexpress</type>
        <cvv>362</cvv>
        <expiresAt>2016-12</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>bfc406e5-8972-4c2a-9181-f2781d9bb99c</id>
      <firstName>Harwell</firstName>
      <lastName>Runsey</lastName>
      <email>hrunseyt@hexun.com</email>
      <phoneNumber>626-753-7454</phoneNumber>
      <cards>
        <number>201407023633047</number>
        <type>diners-club-enroute</type>
        <cvv>262</cvv>
        <expiresAt>2017-03</expiresAt>
      </cards>
      <cards>
        <number>3583512613825168</number>
        <type>jcb</type>
        <cvv>117</cvv>
        <expiresAt>2021-01</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>4a9db666-41f6-4843-80bc-80e7a6029ea0</id>
    <name>Schaefer LLC</name>
    <street>961 Ridgeview Way</street>
    <city>Lloydminster</city>
    <region>Saskatchewan</region>
    <country>Canada</country>
    <clients>
      <id>7170bf84-06cc-42b1-abc7-52ba0d86d97f</id>
      <firstName>Hildegaard</firstName>
      <lastName>Rangall</lastName>
      <email>hrangallu@hao123.com</email>
      <phoneNumber>821-649-8590</phoneNumber>
      <cards>
        <number>6763504253414358</number>
        <type>maestro</type>
        <cvv>605</cvv>
        <expiresAt>2017-02</expiresAt>
      </cards>
      <cards>
        <number>3572871469261859</number>
        <type>jcb</type>
        <cvv>220</cvv>
        <expiresAt>2013-05</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>45efc60b-0f4e-4ed2-a69f-62c73a8d7814</id>
      <firstName>Jacinda</firstName>
      <lastName>Nicolson</lastName>
      <email>jnicolsonv@github.io</email>
      <phoneNumber>589-320-0957</phoneNumber>
      <cards>
        <number>30586811460080</number>
        <type>diners-club-carte-blanche</type>
        <cvv>414</cvv>
        <expiresAt>2013-09</expiresAt>
      </cards>
      <cards>
        <number>3564458341382002</number>
        <type>jcb</type>
        <cvv>258</cvv>
        <expiresAt>2019-08</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>6c7993a5-c528-47ef-aa61-7fb52cf22c06</id>
      <firstName>Kirbie</firstName>
      <lastName>Dameisele</lastName>
      <email>kdameiselew@unblog.fr</email>
      <phoneNumber>335-228-5080</phoneNumber>
      <cards>
        <number>6334932430979855870</number>
        <type>solo</type>
        <cvv>871</cvv>
        <expiresAt>2018-06</expiresAt>
      </cards>
      <cards>
        <number>341357009821895</number>
        <type>americanexpress</type>
        <cvv>268</cvv>
        <expiresAt>2020-12</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>85d00e36-ebc2-4f50-b291-5867acc7e124</id>
    <name>Weber, Gislason and Kozey</name>
    <street>6681 Anzinger Hill</street>
    <city>Fort Wayne</city>
    <region>Indiana</region>
    <country>United States</country>
    <clients>
      <id>d5253b53-e570-4205-a785-c76bdf5535ad</id>
      <firstName>Tove</firstName>
      <lastName>Peron</lastName>
      <email>tperonx@examiner.com</email>
      <phoneNumber>670-142-6711</phoneNumber>
      <cards>
        <number>4917798202330026</number>
        <type>visa-electron</type>
        <cvv>913</cvv>
        <expiresAt>2014-11</expiresAt>
      </cards>
      <cards>
        <number>3538760317893711</number>
        <type>jcb</type>
        <cvv>771</cvv>
        <expiresAt>2021-03</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>f25fd043-6bd9-4467-a916-0883d9688dc8</id>
      <firstName>Susanne</firstName>
      <lastName>Trevarthen</lastName>
      <email>strevartheny@vkontakte.ru</email>
      <phoneNumber>216-544-6593</phoneNumber>
      <cards>
        <number>4017952987517484</number>
        <type>visa</type>
        <cvv>347</cvv>
        <expiresAt>2012-04</expiresAt>
      </cards>
      <cards>
        <number>4026043772173813</number>
        <type>visa-electron</type>
        <cvv>864</cvv>
        <expiresAt>2016-07</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>a467ec8b-f8c4-4782-9642-f00b7a12bc69</id>
      <firstName>Jobye</firstName>
      <lastName>McGarel</lastName>
      <email>jmcgarelz@arstechnica.com</email>
      <phoneNumber>508-164-8072</phoneNumber>
      <cards>
        <number>3588009858211027</number>
        <type>jcb</type>
        <cvv>408</cvv>
        <expiresAt>2019-01</expiresAt>
      </cards>
      <cards>
        <number>30122309202485</number>
        <type>diners-club-carte-blanche</type>
        <cvv>129</cvv>
        <expiresAt>2015-09</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>b99a9977-79a6-4776-9716-203d1d080308</id>
    <name>Sporer LLC</name>
    <street>1596 Dixon Pass</street>
    <city>Peace River</city>
    <region>Alberta</region>
    <country>Canada</country>
    <clients>
      <id>4146f0cd-61eb-4378-be8b-2aa3ff81c92f</id>
      <firstName>Celinda</firstName>
      <lastName>Turland</lastName>
      <email>cturland10@huffingtonpost.com</email>
      <phoneNumber>274-378-5919</phoneNumber>
      <cards>
        <number>5551348028128465</number>
        <type>diners-club-us-ca</type>
        <cvv>436</cvv>
        <expiresAt>2021-04</expiresAt>
      </cards>
      <cards>
        <number>5100149890747473</number>
        <type>mastercard</type>
        <cvv>461</cvv>
        <expiresAt>2021-10</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>035ce9a8-fc8a-4a2e-a8b8-5cfb66404962</id>
      <firstName>Starlene</firstName>
      <lastName>Summerlad</lastName>
      <email>ssummerlad11@bandcamp.com</email>
      <phoneNumber>893-274-6560</phoneNumber>
      <cards>
        <number>3569098131385727</number>
        <type>jcb</type>
        <cvv>720</cvv>
        <expiresAt>2012-10</expiresAt>
      </cards>
      <cards>
        <number>3557790354445659</number>
        <type>jcb</type>
        <cvv>338</cvv>
        <expiresAt>2014-04</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>04cc5cbe-1944-4111-b556-4242f4350cd7</id>
      <firstName>Meier</firstName>
      <lastName>Fripp</lastName>
      <email>mfripp12@tiny.cc</email>
      <phoneNumber>855-368-7477</phoneNumber>
      <cards>
        <number>3581415619161657</number>
        <type>jcb</type>
        <cvv>130</cvv>
        <expiresAt>2015-02</expiresAt>
      </cards>
      <cards>
        <number>4917282607914825</number>
        <type>visa-electron</type>
        <cvv>334</cvv>
        <expiresAt>2013-11</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>45641172-e412-4cc1-a932-d488a210feee</id>
    <name>Little-Denesik</name>
    <street>53 Corben Street</street>
    <city>Honolulu</city>
    <region>Hawaii</region>
    <country>United States</country>
    <clients>
      <id>21a8e107-87a8-4030-a891-80e1f86f8346</id>
      <firstName>Dolorita</firstName>
      <lastName>Huggins</lastName>
      <email>dhuggins13@upenn.edu</email>
      <phoneNumber>450-958-2102</phoneNumber>
      <cards>
        <number>3546321660170171</number>
        <type>jcb</type>
        <cvv>633</cvv>
        <expiresAt>2017-12</expiresAt>
      </cards>
      <cards>
        <number>06045369773302271</number>
        <type>maestro</type>
        <cvv>210</cvv>
        <expiresAt>2019-04</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>c93f5dde-8957-46af-bc09-6f1cb5be0d73</id>
      <firstName>Freddi</firstName>
      <lastName>Kinnar</lastName>
      <email>fkinnar14@nasa.gov</email>
      <phoneNumber>157-891-5308</phoneNumber>
      <cards>
        <number>3532475506960587</number>
        <type>jcb</type>
        <cvv>301</cvv>
        <expiresAt>2020-08</expiresAt>
      </cards>
      <cards>
        <number>4936412339161038349</number>
        <type>switch</type>
        <cvv>895</cvv>
        <expiresAt>2022-01</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>04d22960-f38a-46b0-85a9-f422fee740ac</id>
      <firstName>Perry</firstName>
      <lastName>Conaboy</lastName>
      <email>pconaboy15@edublogs.org</email>
      <phoneNumber>140-361-1701</phoneNumber>
      <cards>
        <number>4041376879051487</number>
        <type>visa</type>
        <cvv>745</cvv>
        <expiresAt>2022-06</expiresAt>
      </cards>
      <cards>
        <number>3564772556355945</number>
        <type>jcb</type>
        <cvv>847</cvv>
        <expiresAt>2017-04</expiresAt>
      </cards>
    </clients>
  </branch>
  <branch>
    <id>f97f489d-5cc4-46a5-b5c1-40d16c8303e1</id>
    <name>Donnelly and Sons</name>
    <street>6851 Golf Court</street>
    <city>Chicago</city>
    <region>Illinois</region>
    <country>United States</country>
    <clients>
      <id>40a21273-a84d-48a9-8b16-131b6db256fc</id>
      <firstName>Marsha</firstName>
      <lastName>Bambery</lastName>
      <email>mbambery16@gnu.org</email>
      <phoneNumber>904-739-6839</phoneNumber>
      <cards>
        <number>3580304767392341</number>
        <type>jcb</type>
        <cvv>256</cvv>
        <expiresAt>2021-04</expiresAt>
      </cards>
      <cards>
        <number>670618689465430035</number>
        <type>laser</type>
        <cvv>998</cvv>
        <expiresAt>2021-04</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>a2796370-5e6e-4e75-8537-13a72f16d92b</id>
      <firstName>Valentia</firstName>
      <lastName>Dutton</lastName>
      <email>vdutton17@trellian.com</email>
      <phoneNumber>245-590-6965</phoneNumber>
      <cards>
        <number>3552297120072952</number>
        <type>jcb</type>
        <cvv>812</cvv>
        <expiresAt>2018-12</expiresAt>
      </cards>
      <cards>
        <number>5602258674071183</number>
        <type>bankcard</type>
        <cvv>548</cvv>
        <expiresAt>2012-09</expiresAt>
      </cards>
    </clients>
    <clients>
      <id>8817ebe0-0079-4673-8e2f-3316a913e543</id>
      <firstName>Willamina</firstName>
      <lastName>Joddens</lastName>
      <email>wjoddens18@csmonitor.com</email>
      <phoneNumber>833-149-2574</phoneNumber>
      <cards>
        <number>3535887542034200</number>
        <type>jcb</type>
        <cvv>920</cvv>
        <expiresAt>2014-09</expiresAt>
      </cards>
      <cards>
        <number>36862695374968</number>
        <type>diners-club-international</type>
        <cvv>289</cvv>
        <expiresAt>2020-11</expiresAt>
      </cards>
    </clients>
  </branch>
</banks>